# Generated by Django 5.0.3 on 2026-06-14 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único como hygiene, exercise, focus', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre visible', max_length=100)),
                ('color_code', models.CharField(help_text='Variable CSS o Hex color', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=30)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='routines.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_of_week', models.CharField(help_text="Días activos, ej: '0,1,2,3,4,5,6'", max_length=100)),
                ('start_time', models.TimeField()),
                ('reminder_minutes', models.PositiveIntegerField(default=0)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('auto_complete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='routines.routinetemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='routinetemplate',
            index=models.Index(fields=['user', 'category', 'active'], name='routines_ro_user_id_673fd9_idx'),
        ),
    ]
