# Generated by Django 5.0.3 on 2026-06-15 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PROGRAMMED', 'Programada'), ('NOTIFIED', 'Notificada'), ('SNOOZED', 'Pospuesta'), ('IN_PROGRESS', 'En Progreso'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada'), ('OMITTED', 'Omitida'), ('EXPIRED', 'Expirada')], default='PROGRAMMED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='routines.routinetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scheduled_start'], name='executions__user_id_d65dd6_idx'), models.Index(fields=['user', 'status'], name='executions__user_id_688730_idx'), models.Index(fields=['user', 'scheduled_start', 'status'], name='executions__user_id_c63568_idx')],
            },
        ),
    ]
