# Generated by Django 5.0.3 on 2026-06-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexecution',
            name='last_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('NOTIFIED', 'Notificada'), ('SNOOZED', 'Pospuesta'), ('IN_PROGRESS', 'En Progreso'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada'), ('OMITTED', 'Omitida'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=20),
        ),
    ]
