# Generated by Django 5.0.3 on 2026-06-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_routineexecution_last_resumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexecution',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
